name: build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: catppuccin/setup-whiskers@v2

      - name: Build
        run: just build

      - name: Create Archive
        run: just zip

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: "catppuccin-snapshot.flex"
          path: catppuccin*.flex
